version: '3.9'

services:
  test-postgres:
    image: postgres:latest
    container_name: test-postgres
    environment:
      POSTGRES_DB: ${TEST_DB__NAME}
      POSTGRES_USER: ${TEST_DB__USER}
      POSTGRES_PASSWORD: ${TEST_DB__PASSWORD}
      POSTGRES_HOST: ${TEST_DB__HOST}
      POSTGRES_PORT: ${TEST_DB__PORT}
    ports:
      - "5433:5432"
    volumes:
      - psql-data:/var/lib/postgresql/todo_app_test/

  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "8000:8000"
    command: "sh /app/entrypoint.sh"
    env_file:
      - .env
    depends_on:
      - test-postgres


volumes:
  psql-data: