version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - psql-data:/var/lib/postgresql/todo_app/

  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "8000:8000"
    command: "sh /app/entrypoint.sh"
    env_file:
      - .env
    depends_on:
      - postgres


volumes:
  psql-data: