version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
      POSTGRES_HOST: ${DB__HOST}
      POSTGRES_PORT: ${DB__PORT}
    ports:
      - "5432:5432"
    volumes:
      - psql-data:/var/lib/postgresql/data

  main-app:
    build:
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "8000:8000"
    command: "sh /app/entrypoint.sh"
    env_file:
      - .env
    depends_on:
      - postgres


volumes:
  psql-data: