version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: todo_app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - psql-data:/var/lib/postgresql/todo_app/

volumes:
  psql-data: