"""empty message

Revision ID: 84be4a782dd0
Revises: 4d41b473d08a
Create Date: 2024-06-26 17:45:42.786218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84be4a782dd0'
down_revision: Union[str, None] = '4d41b473d08a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('descritpion', sa.String(), nullable=True))
    op.add_column('todo', sa.Column('target_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'target_date')
    op.drop_column('todo', 'descritpion')
    # ### end Alembic commands ###
