"""empty message

Revision ID: d68d6526d053
Revises: 84be4a782dd0
Create Date: 2024-06-26 17:51:43.843745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68d6526d053'
down_revision: Union[str, None] = '84be4a782dd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('todo', 'descritpion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('descritpion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('todo', 'description')
    # ### end Alembic commands ###
