"""Empty message.

Revision ID: e8295652504d
Revises: 63cad83fcd81
Create Date: 2024-06-26 18:26:47.324067

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'e8295652504d'
down_revision: Union[str, None] = '63cad83fcd81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
